# Generated by Django 6.0.2 on 2026-02-28 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('score', models.IntegerField()),
                ('date_achieved', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-score', '-date_achieved'],
            },
        ),
    ]
